/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4 */

#ifndef _Included_fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
#define _Included_fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
#ifdef __cplusplus
extern "C" {
#endif
#undef fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4_impwinposx
#define fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4_impwinposx 1110L
#undef fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4_impwinposy
#define fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4_impwinposy 125L
/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    seyHello
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_seyHello
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    isHAMAconnectedSDK4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_isHAMAconnectedSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    GetModelSDK4
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_GetModelSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    InitializeHamaSDK4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_InitializeHamaSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    SystemShutDownSDK4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_SystemShutDownSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    GetStringSDK4
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_GetStringSDK4
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    GetDoubleSDK4
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_GetDoubleSDK4
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    getIntegerSDK4
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_getIntegerSDK4
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    getDetectorDimensionSDK4
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_getDetectorDimensionSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    getChipSizeSDK4
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_getChipSizeSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    getKineticCycleSDK4
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_getKineticCycleSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    setParameterSDK4
 * Signature: (DIIIIIIIIIIDDII)I
 */
JNIEXPORT jint JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_setParameterSDK4
  (JNIEnv *, jclass, jdouble, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jint, jint);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    runSingleScanSDK4
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_runSingleScanSDK4
  (JNIEnv *, jclass);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    runInfiniteLoopSDK4
 * Signature: ([SLfiji/plugin/imaging_fcs/directCameraReadout/control/FrameCounter;)V
 */
JNIEXPORT void JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_runInfiniteLoopSDK4
  (JNIEnv *, jclass, jshortArray, jobject);

/*
 * Class:     fiji_plugin_imaging_fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_DCAM_SDK4
 * Method:    setStopMechanismSDK4
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_fiji_plugin_imaging_1fcs_directCameraReadout_hamadcamsdk4_Hamamatsu_1DCAM_1SDK4_setStopMechanismSDK4
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
