/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiji_plugin_imaging_fcs_new_imfcs_gpu_GpuCorrelator */

#ifndef _Included_fiji_plugin_imaging_fcs_new_imfcs_gpu_GpuCorrelator
#define _Included_fiji_plugin_imaging_fcs_new_imfcs_gpu_GpuCorrelator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fiji_plugin_imaging_fcs_new_imfcs_gpu_GpuCorrelator
 * Method:    calcACF
 * Signature: ([F[D[D[D[D[D[D[D[ILfiji/plugin/imaging_fcs/new_imfcs/gpu/GpuParameters;)V
 */
JNIEXPORT void JNICALL Java_fiji_plugin_imaging_1fcs_new_1imfcs_gpu_GpuCorrelator_calcACF
  (JNIEnv *, jclass, jfloatArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
